version: '2'
services:
  db:
    image: postgres
    ports:
     - "5433:5432"
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/code
    environment:
     - DATABASE_URL=postgres://postgres:@db:5432
    links:
     - db
